In [1]:
%load_ext cudf.pandas
%load_ext cuml.accel

import cudf
import pandas as pd
import cupy as cp
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
import re
from collections import Counter

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

In [17]:
df_train = pd.read_csv('datasets/Quora Questions Pair Dataset/train_preprocessed.csv')
print(type(df_train))
df_train.sample(3)

<class 'pandas.core.frame.DataFrame'>

,question1,question2,is_duplicate
82538,what is the meaning of flagged as needing impr...,how often do you mark questions as needing imp...,1
181918,why are highly productive people well liked,what is the best used car to buy for lakhs in ...,0
51133,how can you find the length and width of a rec...,how do you find the length of the rectangle,0

In [18]:
def tokenize(text):
    return text.split()

In [19]:
all_tokens = []
for col in ['question1', 'question2']:
    for row in df_train[col]:
        all_tokens.extend(tokenize(row))
print(f"Corpus size: {len(all_tokens)}")

Corpus size: 9016420

In [20]:
#get all the words with the number of times they repeat
counter = Counter(all_tokens)
counter

Counter({'the': 381218,
         'what': 324583,
         'is': 303747,
         'a': 280272,
         'i': 226080,
         'how': 220836,
         'in': 217045,
         'to': 212279,
         'do': 170765,
         'of': 164274,
         'are': 149915,
         'and': 135559,
         'can': 114372,
         'for': 104611,
         'you': 96247,
         'my': 87862,
         'why': 84040,
         'it': 75246,
         'best': 70600,
         'on': 60860,
         'does': 59464,
         'or': 46840,
         'have': 44932,
         'be': 44749,
         'if': 44129,
         'which': 43979,
         'some': 41710,
         'that': 40750,
         'get': 40616,
         'with': 39909,
         'should': 39625,
         'not': 39063,
         'an': 37216,
         'from': 35304,
         'your': 34073,
         'india': 29584,
         'will': 29462,
         'people': 26407,
         'when': 26229,
         'who': 26106,
         'at': 25840,
         'like': 25648,
         'good': 24891,
         'would': 24151,
         'there': 23678,
         'as': 23228,
         'about': 21155,
         'am': 21148,
         'between': 20322,
         'one': 20038,
         'did': 19956,
         'we': 19473,
         'most': 19021,
         'quota': 18413,
         'by': 18236,
         'make': 18224,
         'way': 18133,
         'where': 17436,
         'so': 17005,
         'any': 16962,
         'was': 16876,
         'me': 16620,
         'life': 16507,
         'eyes': 16020,
         'they': 15610,
         'tears': 15176,
         'after': 15173,
         'us': 14965,
         'this': 14908,
         'money': 14604,
         'has': 13892,
         'know': 13790,
         'use': 13582,
         'difference': 13454,
         'learn': 13096,
         'new': 12562,
         'much': 12393,
         'someone': 12042,
         'their': 11794,
         'all': 11570,
         'many': 11505,
         'think': 11504,
         'work': 11324,
         'indian': 10799,
         'than': 10675,
         'trump': 10630,
         'more': 10608,
         'find': 10582,
         'ever': 10576,
         'but': 10026,
         'without': 10022,
         'world': 9926,
         'become': 9917,
         'start': 9897,
         'online': 9772,
         'first': 9724,
         'better': 9704,
         'other': 9690,
         'out': 9593,
         'he': 9579,
         'want': 9577,
         'year': 9356,
         'up': 8747,
         'mean': 8746,
         'job': 8709,
         'into': 8571,
         'see': 8556,
         'english': 8526,
         'go': 8483,
         'could': 8169,
         'feel': 8008,
         'love': 7974,
         'day': 7870,
         'take': 7843,
         'possible': 7809,
         'sex': 7315,
         'things': 7294,
         'questions': 7288,
         'notes': 7158,
         'phone': 7103,
         'were': 7065,
         'engineering': 6953,
         'person': 6921,
         'buy': 6920,
         'really': 6919,
         'ways': 6914,
         'account': 6870,
         'weight': 6855,
         'used': 6822,
         'old': 6776,
         'donald': 6745,
         'long': 6665,
         'google': 6563,
         'them': 6545,
         'girl': 6523,
         'being': 6407,
         'number': 6345,
         'her': 6329,
         'improve': 6248,
         'his': 6202,
         'using': 6172,
         'books': 6113,
         'business': 6056,
         'need': 6037,
         'facebook': 5993,
         'no': 5953,
         'language': 5900,
         'stop': 5866,
         'lose': 5854,
         'movie': 5823,
         'different': 5782,
         'thing': 5735,
         'black': 5719,
         'book': 5689,
         'been': 5684,
         'its': 5679,
         'free': 5592,
         'data': 5553,
         'now': 5544,
         'just': 5525,
         'war': 5497,
         'years': 5496,
         'going': 5464,
         'compare': 5424,
         'question': 5407,
         'had': 5383,
         'programming': 5371,
         'still': 5298,
         'help': 5161,
         'only': 5149,
         'instagram': 5111,
         'president': 5093,
         'before': 5090,
         'company': 5087,
         'change': 5080,
         'happen': 5048,
         'women': 5043,
         'email': 5035,
         'movies': 5033,
         'app': 5002,
         'she': 4986,
         'real': 4905,
         'college': 4868,
         'over': 4834,
         'prepare': 4804,
         'under': 4793,
         'android': 4778,
         'win': 4756,
         'examples': 4711,
         'ask': 4703,
         'computer': 4686,
         'clinton': 4677,
         'live': 4654,
         'back': 4640,
         'country': 4632,
         'website': 4578,
         'while': 4576,
         'iphone': 4562,
         'learning': 4537,
         'cannot': 4515,
         'bad': 4509,
         'top': 4497,
         'system': 4479,
         'important': 4465,
         'our': 4460,
         'match': 4426,
         'study': 4330,
         'made': 4294,
         'hillary': 4282,
         'same': 4275,
         'increase': 4271,
         'software': 4259,
         'through': 4245,
         'school': 4240,
         'science': 4209,
         'read': 4203,
         'two': 4166,
         'home': 4148,
         'car': 4081,
         'government': 4070,
         'water': 4014,
         'him': 4006,
         'earn': 4001,
         'card': 3996,
         'during': 3993,
         'men': 3912,
         'mobile': 3865,
         'student': 3862,
         'high': 3852,
         'favourite': 3845,
         'say': 3820,
         'name': 3798,
         'exam': 3791,
         'energy': 3778,
         'university': 3742,
         'word': 3736,
         'give': 3729,
         'anyone': 3716,
         'getting': 3685,
         'earth': 3638,
         'next': 3610,
         'china': 3579,
         'companies': 3565,
         'right': 3561,
         'com': 3523,
         'true': 3521,
         'days': 3511,
         'average': 3473,
         'web': 3461,
         'done': 3451,
         'then': 3436,
         'laptop': 3428,
         'doing': 3428,
         'come': 3426,
         'friend': 3424,
         'career': 3403,
         'even': 3374,
         'tell': 3372,
         'tech': 3367,
         'hair': 3359,
         'video': 3356,
         'youtube': 3344,
         'look': 3305,
         'interview': 3294,
         'answer': 3294,
         'social': 3284,
         'guy': 3268,
         'own': 3264,
         'man': 3264,
         'bank': 3261,
         'travel': 3257,
         'friends': 3229,
         'write': 3219,
         'meaning': 3208,
         'safe': 3207,
         'cost': 3185,
         'watch': 3175,
         'students': 3146,
         'working': 3145,
         'big': 3138,
         'off': 3122,
         'password': 3110,
         'non': 3107,
         'mode': 3103,
         'pakistan': 3101,
         'eat': 3086,
         'pm': 3081,
         'human': 3076,
         'relationship': 3074,
         'rupee': 3067,
         'experience': 3065,
         'happens': 3058,
         'place': 3051,
         'girls': 3035,
         'game': 3033,
         'food': 3032,
         'very': 3015,
         'rid': 3014,
         'having': 3013,
         'mind': 2997,
         'service': 2945,
         'play': 2927,
         'countries': 2926,
         'whatsapp': 2925,
         'myself': 2913,
         'major': 2881,
         'keep': 2869,
         'future': 2858,
         'history': 2854,
         'age': 2846,
         'employees': 2844,
         'affect': 2831,
         'end': 2826,
         'tips': 2812,
         'download': 2796,
         'too': 2769,
         'state': 2769,
         'great': 2769,
         'engineer': 2769,
         'white': 2767,
         'believe': 2763,
         'last': 2755,
         'process': 2745,
         'around': 2742,
         'skills': 2725,
         'java': 2718,
         'body': 2714,
         'exist': 2711,
         'chinese': 2710,
         'effects': 2707,
         'election': 2707,
         'test': 2706,
         'every': 2704,
         'delhi': 2690,
         'against': 2684,
         'support': 2680,
         'makes': 2668,
         'marketing': 2667,
         'god': 2655,
         'mechanical': 2649,
         'class': 2647,
         'create': 2643,
         'differences': 2642,
         'girlfriend': 2639,
         'hard': 2636,
         'month': 2628,
         'internet': 2624,
         'places': 2613,
         'interesting': 2605,
         'got': 2603,
         'states': 2585,
         'visit': 2573,
         'making': 2567,
         'music': 2566,
         'american': 2566,
         'police': 2560,
         'united': 2516,
         'pay': 2488,
         'these': 2486,
         'windows': 2486,
         'power': 2484,
         'market': 2475,
         'worth': 2475,
         'user': 2473,
         'code': 2463,
         'never': 2449,
         'song': 2434,
         'salary': 2422,
         'each': 2420,
         'series': 2416,
         'woman': 2414,
         'control': 2396,
         'actually': 2384,
         'america': 2379,
         'course': 2365,
         'pc': 2353,
         'culture': 2346,
         'answers': 2345,
         'looking': 2341,
         'site': 2340,
         'self': 2336,
         'available': 2333,
         'something': 2319,
         'fat': 2310,
         'hotel': 2304,
         'always': 2299,
         'considered': 2298,
         'today': 2288,
         'another': 2272,
         'months': 2270,
         'common': 2268,
         'per': 2256,
         'development': 2252,
         'mia': 2249,
         'bangalore': 2247,
         'die': 2247,
         'writing': 2245,
         'economy': 2243,
         'universities': 2242,
         'light': 2239,
         'apply': 2239,
         'delete': 2239,
         'such': 2230,
         'open': 2226,
         'jobs': 2225,
         'parents': 2201,
         'cat': 2176,
         'space': 2161,
         'happened': 2148,
         'idea': 2144,
         'type': 2141,
         'problem': 2141,
         'deal': 2140,
         'dark': 2138,
         'score': 2138,
         'kind': 2127,
         'show': 2123,
         'services': 2123,
         'review': 2119,
         'speed': 2118,
         'list': 2118,
         'universe': 2115,
         'etc': 2103,
         'design': 2100,
         'build': 2095,
         'behind': 2093,
         'note': 2091,
         'living': 2083,
         'post': 2079,
         'hack': 2077,
         'purpose': 2076,
         'able': 2075,
         'center': 2071,
         'worst': 2068,
         'well': 2068,
         'songs': 2064,
         'education': 2064,
         'games': 2053,
         'near': 2049,
         'add': 2042,
         'run': 2039,
         'date': 2033,
         'period': 2031,
         'family': 2026,
         'civil': 2024,
         'presidential': 2022,
         'seen': 2022,
         'because': 2019,
         'plan': 2019,
         'reason': 2014,
         'instead': 2008,
         'reduce': 2007,
         'call': 2006,
         'law': 2005,
         'also': 2005,
         'differ': 2005,
         'current': 2004,
         'digital': 2004,
         'wrong': 2004,
         'popular': 2003,
         'air': 1999,
         'cause': 1998,
         'asked': 1992,
         'private': 1989,
         'height': 1986,
         'websites': 1985,
         'technology': 1983,
         'management': 1983,
         'join': 1976,
         'majors': 1974,
         'loss': 1968,
         'degree': 1966,
         'main': 1963,
         'apps': 1960,
         'apple': 1959,
         'program': 1947,
         'boyfriend': 1939,
         'city': 1937,
         'easily': 1936,
         'order': 1933,
         'machine': 1922,
         'traffic': 1920,
         'international': 1918,
         'search': 1916,
         'hate': 1916,
         'canada': 1912,
         'sentence': 1907,
         'facts': 1900,
         'times': 1899,
         'based': 1897,
         'public': 1896,
         'sleep': 1893,
         'biggest': 1892,
         'pregnant': 1885,
         'visa': 1884,
         'stay': 1884,
         'down': 1882,
         'death': 1869,
         'causes': 1865,
         'credit': 1854,
         'both': 1848,
         'child': 1844,
         'choose': 1843,
         'less': 1843,
         'currency': 1843,
         'benefits': 1843,
         'vote': 1842,
         'sites': 1839,
         'python': 1836,
         'media': 1833,
         'compared': 1822,
         'indians': 1821,
         'part': 1812,
         'gain': 1811,
         'small': 1809,
         'successful': 1802,
         'drug': 1797,
         'face': 1797,
         'california': 1787,
         'house': 1786,
         'recover': 1785,
         'wear': 1780,
         'startup': 1777,
         'decision': 1771,
         'fast': 1765,
         'move': 1764,
         'dog': 1763,
         'fall': 1760,
         'videos': 1756,
         'foreign': 1754,
         'battle': 1751,
         'story': 1748,
         'products': 1747,
         'terms': 1747,
         'stock': 1741,
         'legal': 1736,
         'remove': 1733,
         'level': 1731,
         'value': 1726,
         'given': 1724,
         'normal': 1720,
         'preparation': 1718,
         'health': 1717,
         'amazon': 1716,
         'medical': 1714,
         'ban': 1710,
         'overcome': 1709,
         'humans': 1707,
         'views': 1698,
         'product': 1694,
         'found': 1694,
         'banning': 1689,
         'invest': 1688,
         'point': 1687,
         'case': 1682,
         'ones': 1669,
         'profile': 1668,
         'red': 1663,
         'created': 1663,
         'project': 1658,
         'form': 1657,
         'coaching': 1653,
         'called': 1640,
         'again': 1637,
         'rate': 1637,
         'group': 1630,
         'solar': 1629,
         'follow': 1628,
         'theory': 1627,
         'gate': 1625,
         'known': 1622,
         'snapshot': 1621,
         'drive': 1615,
         'side': 1609,
         'research': 1605,
         'hours': 1604,
         'easiest': 1604,
         'ideas': 1604,
         'message': 1599,
         'alcohol': 1598,
         'physics': 1594,
         'speak': 1593,
         'porn': 1593,
         'effect': 1587,
         'color': 1584,
         'must': 1579,
         'grow': 1578,
         'easy': 1577,
         'yourself': 1577,
         'left': 1577,
         'lot': 1569,
         'send': 1563,
         'low': 1560,
         'matter': 1559,
         'mac': 1557,
         'sell': 1555,
         'week': 1551,
         'others': 1549,
         'single': 1543,
         'view': 1541,
         'advice': 1539,
         'australia': 1537,
         'night': 1535,
         'full': 1534,
         'application': 1533,
         'talk': 1532,
         'anything': 1532,
         'quality': 1531,
         'put': 1527,
         'pro': 1525,
         'pros': 1523,
         'germany': 1519,
         'cons': 1518,
         'correct': 1517,
         'information': 1516,
         'tax': 1512,
         'children': 1512,
         'russia': 1510,
         'faster': 1508,
         'jim': 1507,
         'required': 1501,
         'bollywood': 1501,
         'sydney': 1499,
         'famous': 1498,
         'messages': 1492,
         'improvement': 1491,
         'guys': 1491,
         'says': 1490,
         'solve': 1485,
         'green': 1479,
         'marks': 1479,
         'star': 1477,
         'size': 1476,
         'eye': 1474,
         'file': 1472,
         'field': 1470,
         'institute': 1469,
         'mumbai': 1469,
         'moment': 1465,
         'kill': 1458,
         'advantages': 1458,
         'daily': 1457,
         'studying': 1457,
         'distance': 1456,
         'courses': 1455,
         'short': 1452,
         'south': 1449,
         'options': 1446,
         'security': 1444,
         'marriage': 1444,
         'desert': 1442,
         'rupees': 1441,
         'similar': 1440,
         'cell': 1434,
         'languages': 1432,
         'suicide': 1428,
         'sim': 1421,
         'gas': 1416,
         'force': 1414,
         'effective': 1410,
         'happy': 1408,
         'general': 1408,
         'problems': 1408,
         'provider': 1407,
         'source': 1404,
         'words': 1404,
         'set': 1404,
         'simple': 1399,
         'area': 1399,
         'avoid': 1398,
         'those': 1395,
         'started': 1395,
         'investment': 1392,
         'industry': 1392,
         'impact': 1390,
         'developer': 1385,
         'term': 1384,
         'healthy': 1383,
         'function': 1381,
         'blood': 1378,
         'safety': 1377,
         'oil': 1376,
         'lost': 1376,
         'deleted': 1373,
         'era': 1372,
         'mass': 1371,
         'suitable': 1369,
         'three': 1360,
         'dream': 1356,
         'text': 1353,
         'brain': 1344,
         'likes': 1343,
         'blog': 1343,
         'exactly': 1342,
         'often': 1342,
         'photos': 1336,
         'colleges': 1335,
         'beautiful': 1322,
         'let': 1319,
         'turn': 1316,
         'care': 1314,
         'ups': 1311,
         'develop': 1311,
         'graduate': 1304,
         'model': 1303,
         'fix': 1300,
         'electrical': 1298,
         'page': 1298,
         'few': 1297,
         'cold': 1295,
         'past': 1294,
         'types': 1293,
         'japan': 1290,
         'chemical': 1290,
         'engine': 1289,
         'party': 1287,
         'net': 1286,
         'share': 1285,
         'pop': 1283,
         'heard': 1282,
         'across': 1282,
         'away': 1278,
         'married': 1278,
         'said': 1276,
         'reasons': 1275,
         'pass': 1273,
         'price': 1273,
         'gay': 1270,
         'picture': 1270,
         'key': 1270,
         'moon': 1268,
         'male': 1267,
         'store': 1265,
         'dogs': 1264,
         'japanese': 1261,
         'address': 1261,
         'check': 1259,
         'proposed': 1256,
         'contact': 1255,
         'leave': 1255,
         'office': 1252,
         'training': 1252,
         'numbers': 1251,
         'understand': 1249,
         'north': 1247,
         'second': 1247,
         'basic': 1247,
         'team': 1245,
         'line': 1243,
         'female': 1242,
         'letter': 1240,
         'cut': 1240,
         'bill': 1239,
         'eating': 1238,
         'offer': 1237,
         'enough': 1236,
         'coming': 1232,
         'fight': 1231,
         'related': 1229,
         'hindi': 1229,
         'religion': 1228,
         'late': 1227,
         'obama': 1224,
         'exams': 1222,
         'access': 1221,
         'matchbook': 1221,
         'network': 1218,
         'once': 1214,
         'chances': 1212,
         'samsung': 1212,
         'meet': 1209,
         'boy': 1208,
         'everyone': 1208,
         'wife': 1207,
         'americans': 1200,
         'taking': 1195,
         'british': 1194,
         're': 1192,
         'prime': 1192,
         'quickly': 1191,
         'hyderabad': 1186,
         'cd': 1186,
         'topics': 1183,
         'political': 1182,
         'film': 1182,
         'calculate': 1182,
         'users': 1178,
         'balance': 1174,
         'gold': 1173,
         'precautions': 1173,
         'rich': 1172,
         'personal': 1171,
         'penis': 1170,
         'yes': 1167,
         'smart': 1165,
         'hollywood': 1165,
         'everything': 1165,
         'handling': 1165,
         'since': 1165,
         'county': 1165,
         'panel': 1163,
         'national': 1162,
         'narendra': 1162,
         'chance': 1160,
         'gift': 1159,
         'mix': 1156,
         'changed': 1156,
         'convert': 1153,
         'try': 1144,
         'train': 1144,
         'following': 1142,
         'army': 1141,
         'pune': 1141,
         'drink': 1139,
         'installation': 1139,
         'depression': 1138,

In [21]:
# build vocab of all the words with 5 or more occurences
MIN_COUNT = 4
vocab = ['<pad>','<unk>'] + [w for w,c in counter.items() if c >= MIN_COUNT]
vocab

['<pad>',
 '<unk>',
 'what',
 'is',
 'the',
 'step',
 'by',
 'guide',
 'to',
 'invest',
 'in',
 'share',
 'market',
 'india',
 'story',
 'of',
 'kohinoor',
 'kos',
 'i',
 'door',
 'diamond',
 'how',
 'can',
 'increase',
 'speed',
 'my',
 'internet',
 'connection',
 'while',
 'using',
 'a',
 'van',
 'why',
 'am',
 'mentally',
 'very',
 'lonely',
 'solve',
 'it',
 'which',
 'one',
 'dissolve',
 'water',
 'quickly',
 'sugar',
 'salt',
 'methane',
 'and',
 'carbon',
 'oxide',
 'astrology',
 'capricorn',
 'sun',
 'cap',
 'moon',
 'rising',
 'does',
 'that',
 'say',
 'about',
 'me',
 'should',
 'buy',
 'iago',
 'be',
 'good',
 'geologist',
 'when',
 'do',
 'you',
 'use',
 'instead',
 'motorola',
 'company',
 'hack',
 'charter',
 'dix',
 'method',
 'find',
 'separation',
 'slits',
 'fresnel',
 'baptism',
 'read',
 'youtube',
 'comments',
 'make',
 'physics',
 'easy',
 'learn',
 'was',
 'your',
 'first',
 'sexual',
 'experience',
 'like',
 'are',
 'laws',
 'change',
 'status',
 'from',
 'student',
 'visa',
 'green',
 'card',
 'us',
 'they',
 'compare',
 'immigration',
 'canada',
 'would',
 'trump',
 'presidency',
 'mean',
 'for',
 'current',
 'international',
 'master’a',
 'students',
 'on',
 'an',
 'manipulation',
 'girls',
 'want',
 'friends',
 'with',
 'guy',
 'reject',
 'so',
 'many',
 'quota',
 'users',
 'posting',
 'questions',
 'readily',
 'answered',
 'google',
 'best',
 'digital',
 'marketing',
 'institution',
 'bangalore',
 'rockets',
 'look',
 'white',
 'causing',
 'someone',
 'jealous',
 'not',
 'ask',
 'much',
 'he',
 'every',
 'tears',
 'eyes',
 'at',
 'clock',
 'numbers',
 'same',
 'some',
 'tips',
 'making',
 'through',
 'job',
 'interview',
 'process',
 'medicines',
 'web',
 'application',
 'society',
 'place',
 'too',
 'importance',
 'sports',
 'way',
 'money',
 'online',
 'prepare',
 'final',
 'law',
 'thing',
 'better',
 'special',
 'cares',
 'nose',
 'gets',
 'stuffy',
 'during',
 'night',
 'game',
 'thrones',
 'villain',
 'most',
 'likely',
 'give',
 'mercy',
 'united',
 'states',
 'government',
 'still',
 'blacklist',
 'employment',
 'etc',
 'citizens',
 'because',
 'their',
 'political',
 'views',
 'travel',
 'website',
 'spain',
 'people',
 'think',
 'obama',
 'will',
 'try',
 'take',
 'guns',
 'away',
 'year',
 'old',
 'improve',
 'skills',
 'or',
 'become',
 'entrepreneur',
 'next',
 'few',
 'years',
 'girlfriend',
 'asks',
 'her',
 'boyfriend',
 'did',
 'choose',
 'makes',
 'reply',
 'we',
 'ups',
 'stall',
 'aka',
 'wings',
 'fully',
 'swept',
 'back',
 'slavs',
 'squat',
 'expect',
 'cognizant',
 'confirmation',
 'mail',
 'month',
 'day',
 'trading',
 'being',
 'kid',
 'rebel',
 'worth',
 'long',
 'run',
 'universities',
 'record',
 'recruit',
 'new',
 'grads',
 'majors',
 'looking',
 'quickest',
 'instagram',
 'followers',
 'darth',
 'vader',
 'fought',
 'maul',
 'star',
 'wars',
 'legends',
 'stages',
 'breaking',
 'up',
 'between',
 'couple',
 'happens',
 'after',
 'emotionally',
 'whether',
 'its',
 'male',
 'female',
 'examples',
 'products',
 'crude',
 'oil',
 'career',
 'launcher',
 'rib',
 'grade',
 'preparation',
 'blu',
 'ray',
 'play',
 'regular',
 'player',
 'if',
 'she',
 'always',
 'sad',
 'memorable',
 'have',
 'ever',
 'eaten',
 'get',
 'affects',
 'as',
 'tax',
 'officers',
 'difficult',
 'into',
 'sri',
 'who',
 'israel',
 'friend',
 'rap',
 'songs',
 'dance',
 'suddenly',
 'logged',
 'off',
 'email',
 'cannot',
 'remember',
 'password',
 'just',
 'realized',
 'recovery',
 'no',
 'longer',
 'alive',
 'ways',
 'french',
 'download',
 'content',
 'kicks',
 'torrent',
 'without',
 'registration',
 'normal',
 'dark',
 'ring',
 'around',
 'iris',
 'eye',
 'harry',
 'potter',
 'book',
 'cursed',
 'child',
 'depressed',
 'where',
 'european',
 'family',
 'office',
 'database',
 'java',
 'programming',
 'language',
 'made',
 'store',
 'energy',
 'produced',
 'lightning',
 'review',
 'performance',
 'testing',
 'cost',
 'privacy',
 'germany',
 'come',
 'else',
 'lost',
 'gain',
 'types',
 'immunity',
 'narcissistic',
 'personality',
 'disorder',
 'speak',
 'english',
 'fluently',
 'helpful',
 'quickbooks',
 'auto',
 'data',
 'support',
 'phone',
 'number',
 'recover',
 'corrupted',
 'files',
 'richest',
 'gambler',
 'all',
 'reach',
 'his',
 'level',
 'fire',
 'bullet',
 'backward',
 'aircraft',
 'going',
 'faster',
 'than',
 'backwards',
 'prevent',
 'breast',
 'cancer',
 'log',
 'out',
 'account',
 'purpose',
 'life',
 'bop',
 'strip',
 'muslims',
 'christians',
 'indian',
 'citizenship',
 'put',
 'them',
 'boats',
 'rohingya',
 'burma',
 'right',
 'etiquette',
 'wishing',
 'jehovah',
 'witness',
 'happy',
 'birthday',
 'wants',
 'open',
 'commercial',
 'pm',
 'radio',
 'station',
 'any',
 'city',
 'procedure',
 'swiss',
 'despise',
 'asians',
 'high',
 'salary',
 'income',
 'jobs',
 'field',
 'biotechnology',
 'height',
 'also',
 'were',
 'major',
 'effects',
 'cambodia',
 'earthquake',
 'these',
 'kamchatka',
 'earthquakes',
 'difference',
 'fairness',
 'gaming',
 'laptop',
 'under',
 'warrior',
 'proving',
 'grounds',
 'part',
 'reference',
 'class',
 'national',
 'institute',
 'technology',
 'kurukshetra',
 'social',
 'nick',
 'surathkal',
 'romantic',
 'movies',
 'causes',
 'nightmare',
 'abstract',
 'expressionism',
 'painting',
 'printing',
 'work',
 'attend',
 'catch',
 'jeremy',
 'earnhardt',
 'horcrux',
 'associate',
 'product',
 'manager',
 'programs',
 'early',
 'join',
 'management',
 'rewarding',
 'skype',
 'busy',
 'there',
 'really',
 'war',
 'pakistan',
 'over',
 'fri',
 'attack',
 'ronald',
 'reagan',
 'mannerism',
 'speech',
 'strategies',
 'union',
 'civil',
 'fiction',
 'novel',
 'forgot',
 'recent',
 'demonisation',
 'results',
 'higher',
 'gap',
 'heard',
 'hacking',
 'love',
 'pity',
 'competitive',
 'hiring',
 'republic',
 'bank',
 'helps',
 'spam',
 'ranking',
 'adjustment',
 'search',
 'watch',
 'subtitles',
 'powerful',
 'country',
 'world',
 'obtain',
 'instant',
 'ulcer',
 'pain',
 'relief',
 'china',
 'food',
 'taking',
 'advantage',
 'cry',
 'stick',
 'tongues',
 'pictures',
 'ending',
 'depressing',
 'mind',
 'blowing',
 'computer',
 'tools',
 'exist',
 'know',
 'toothbrush',
 'wet',
 'dry',
 'before',
 'applying',
 'toothpaste',
 'question',
 'marked',
 'needing',
 'improvement',
 'neutral',
 'state',
 'buffer',
 'mineral',
 'holds',
 'highest',
 'electrical',
 'charge',
 'greatest',
 'mystery',
 'universe',
 'alternative',
 'machine',
 'learning',
 'block',
 'sanctions',
 'against',
 'cash',
 'mohammad',
 'jim',
 'chief',
 'mood',
 'char',
 'future',
 'budget',
 'excessive',
 'amounts',
 'vitamin',
 'cause',
 'miscarriage',
 'ash',
 'glass',
 'pay',
 'scale',
 'two',
 'access',
 'turbo',
 'mantras',
 'six',
 'party',
 'talks',
 'successful',
 'register',
 'domain',
 'site',
 'older',
 'men',
 'attracted',
 'young',
 'women',
 'strongest',
 'structure',
 'shape',
 'compression',
 'matter',
 'humans',
 'selfish',
 'evil',
 'endocytosis',
 'active',
 'passive',
 'transport',
 'hair',
 'bald',
 'head',
 'ideal',
 'retirement',
 'our',
 'stance',
 'websites',
 'escorts',
 'polo',
 'diesel',
 'grand',
 'petrol',
 'black',
 'hole',
 'mass',
 'morgan',
 'freeman',
 'correct',
 'says',
 'only',
 'stop',
 'racism',
 'talking',
 'fab',
 'currently',
 'offer',
 'employees',
 'stock',
 'options',
 'russ',
 'distribute',
 'identical',
 'pencils',
 'each',
 'least',
 'pencil',
 'hire',
 'jerry',
 'seinfeld',
 'hours',
 'days',
 'late',
 'rabies',
 'vaccine',
 'possible',
 'non',
 'bite',
 'exposure',
 'britain',
 'ruled',
 'afraid',
 'working',
 'red',
 'keep',
 'keys',
 'age',
 'lose',
 'virginity',
 'could',
 'smoke',
 'secretly',
 'monetize',
 'videos',
 'upload',
 'copyright',
 'then',
 'chances',
 'may',
 'switch',
 'canon',
 'leila',
 'lux',
 'members',
 'moderation',
 'nobody',
 'answer',
 'funniest',
 'joke',
 'got',
 'london',
 '£',
 'deduction',
 'plus',
 'advice',
 'monthly',
 'expenses',
 'saving',
 'stereotypes',
 'kingdom',
 'twitter',
 'business',
 'source',
 'transfer',
 'skill',
 'paypal',
 'earphone',
 'deep',
 'bass',
 'eligible',
 'susanna',
 'saudi',
 'jana',
 'forward',
 'engineering',
 'fields',
 'suit',
 'abusing',
 'gross',
 'towns',
 'kerala',
 'confidence',
 'anyone',
 'see',
 'relation',
 'greek',
 'gods',
 'hindu',
 'apple',
 'music',
 'notify',
 'fixed',
 'fund',
 'live',
 'cologne',
 'robert',
 'de',
 'nero',
 'al',
 'pacino',
 'more',
 'prefer',
 'small',
 'families',
 'animals',
 'simple',
 'stupid',
 'deleted',
 'chats',
 'addicted',
 'hired',
 'private',
 'ordered',
 'follow',
 'other',
 'startup',
 'accelerator',
 'check',
 'wifi',
 'history',
 'android',
 'phones',
 'significance',
 'battle',
 'somme',
 'this',
 'contrast',
 'rostov',
 'creative',
 'college',
 'admissions',
 'essay',
 'happen',
 'cover',
 'patch',
 'pursue',
 'different',
 'things',
 'ben',
 'affect',
 'shine',
 'christian',
 'bale',
 'batman',
 'start',
 'hyderabad',
 'possessive',
 'wife',
 'lord',
 'krishna',
 'combination',
 'courses',
 'along',
 'enhance',
 'screenshot',
 'mac',
 'executive',
 'recruiter',
 'psychological',
 'need',
 'collecting',
 'fulfill',
 'must',
 'shows',
 'die',
 'fluent',
 'chinese',
 'demobilization',
 'rupees',
 'notes',
 'real',
 'estate',
 'sector',
 'easiest',
 'billionaire',
 'willing',
 'free',
 'lectures',
 'conduct',
 'workshop',
 'colleges',
 'robotics',
 'hate',
 'hillary',
 'clinton',
 'periods',
 'regarded',
 'unclean',
 'such',
 'prevented',
 'rituals',
 'hinduism',
 'atheism',
 'lack',
 'belief',
 'term',
 'god',
 'jack',
 'dorsey',
 'quotes',
 'lessons',
 'assassin',
 'creed',
 'series',
 'inlet',
 'printers',
 'color',
 'ink',
 'documents',
 'creativity',
 'important',
 'continue',
 'presidential',
 'campaign',
 'democratic',
 'candidate',
 'headphones',
 'antenna',
 'channels',
 'mobile',
 'companies',
 'install',
 'inbuilt',
 'able',
 'growth',
 'technologies',
 'automation',
 'engineers',
 'apart',
 'disadvantages',
 'listing',
 'derivatives',
 'object',
 'position',
 'respect',
 'continuous',
 'neutron',
 'spa',
 'enough',
 'top',
 'harvard',
 'profitable',
 'trade',
 'binary',
 'utilize',
 'avoid',
 'depression',
 'security',
 'earn',
 'code',
 'japan',
 'sentences',
 'word',
 'another',
 'billion',
 'dollar',
 'lottery',
 'jackpot',
 'scary',
 'drive',
 'road',
 'hand',
 'given',
 'turns',
 'create',
 'shell',
 'terminal',
 'linux',
 'cognition',
 'perception',
 'cowl',
 'total',
 'waiting',
 'list',
 'generations',
 'champions',
 'league',
 'drinking',
 'liners',
 'unhealthy',
 'great',
 'lakes',
 'wildlife',
 'lake',
 'presa',
 'porn',
 'stars',
 'supporters',
 'feel',
 'walking',
 'promises',
 'worried',
 'others',
 'opinions',
 'potty',
 'train',
 'months',
 'pinball',
 'jump',
 'rope',
 'five',
 'minutes',
 'calories',
 'test',
 'gate',
 'stream',
 'material',
 'understanding',
 'algorithmic',
 'analysis',
 'newbie',
 'temperament',
 'husky',
 'mix',
 'balls',
 'weigh',
 'has',
 'weight',
 'heavier',
 'lighter',
 'odd',
 'ball',
 'weighs',
 'raisin',
 'walter',
 'beneath',
 'argue',
 'signs',
 ...]

In [22]:
# generate index of all the words
word2idx = {w:i for i,w in enumerate(vocab)}
word2idx

{'<pad>': 0,
 '<unk>': 1,
 'what': 2,
 'is': 3,
 'the': 4,
 'step': 5,
 'by': 6,
 'guide': 7,
 'to': 8,
 'invest': 9,
 'in': 10,
 'share': 11,
 'market': 12,
 'india': 13,
 'story': 14,
 'of': 15,
 'kohinoor': 16,
 'kos': 17,
 'i': 18,
 'door': 19,
 'diamond': 20,
 'how': 21,
 'can': 22,
 'increase': 23,
 'speed': 24,
 'my': 25,
 'internet': 26,
 'connection': 27,
 'while': 28,
 'using': 29,
 'a': 30,
 'van': 31,
 'why': 32,
 'am': 33,
 'mentally': 34,
 'very': 35,
 'lonely': 36,
 'solve': 37,
 'it': 38,
 'which': 39,
 'one': 40,
 'dissolve': 41,
 'water': 42,
 'quickly': 43,
 'sugar': 44,
 'salt': 45,
 'methane': 46,
 'and': 47,
 'carbon': 48,
 'oxide': 49,
 'astrology': 50,
 'capricorn': 51,
 'sun': 52,
 'cap': 53,
 'moon': 54,
 'rising': 55,
 'does': 56,
 'that': 57,
 'say': 58,
 'about': 59,
 'me': 60,
 'should': 61,
 'buy': 62,
 'iago': 63,
 'be': 64,
 'good': 65,
 'geologist': 66,
 'when': 67,
 'do': 68,
 'you': 69,
 'use': 70,
 'instead': 71,
 'motorola': 72,
 'company': 73,
 'hack': 74,
 'charter': 75,
 'dix': 76,
 'method': 77,
 'find': 78,
 'separation': 79,
 'slits': 80,
 'fresnel': 81,
 'baptism': 82,
 'read': 83,
 'youtube': 84,
 'comments': 85,
 'make': 86,
 'physics': 87,
 'easy': 88,
 'learn': 89,
 'was': 90,
 'your': 91,
 'first': 92,
 'sexual': 93,
 'experience': 94,
 'like': 95,
 'are': 96,
 'laws': 97,
 'change': 98,
 'status': 99,
 'from': 100,
 'student': 101,
 'visa': 102,
 'green': 103,
 'card': 104,
 'us': 105,
 'they': 106,
 'compare': 107,
 'immigration': 108,
 'canada': 109,
 'would': 110,
 'trump': 111,
 'presidency': 112,
 'mean': 113,
 'for': 114,
 'current': 115,
 'international': 116,
 'master’a': 117,
 'students': 118,
 'on': 119,
 'an': 120,
 'manipulation': 121,
 'girls': 122,
 'want': 123,
 'friends': 124,
 'with': 125,
 'guy': 126,
 'reject': 127,
 'so': 128,
 'many': 129,
 'quota': 130,
 'users': 131,
 'posting': 132,
 'questions': 133,
 'readily': 134,
 'answered': 135,
 'google': 136,
 'best': 137,
 'digital': 138,
 'marketing': 139,
 'institution': 140,
 'bangalore': 141,
 'rockets': 142,
 'look': 143,
 'white': 144,
 'causing': 145,
 'someone': 146,
 'jealous': 147,
 'not': 148,
 'ask': 149,
 'much': 150,
 'he': 151,
 'every': 152,
 'tears': 153,
 'eyes': 154,
 'at': 155,
 'clock': 156,
 'numbers': 157,
 'same': 158,
 'some': 159,
 'tips': 160,
 'making': 161,
 'through': 162,
 'job': 163,
 'interview': 164,
 'process': 165,
 'medicines': 166,
 'web': 167,
 'application': 168,
 'society': 169,
 'place': 170,
 'too': 171,
 'importance': 172,
 'sports': 173,
 'way': 174,
 'money': 175,
 'online': 176,
 'prepare': 177,
 'final': 178,
 'law': 179,
 'thing': 180,
 'better': 181,
 'special': 182,
 'cares': 183,
 'nose': 184,
 'gets': 185,
 'stuffy': 186,
 'during': 187,
 'night': 188,
 'game': 189,
 'thrones': 190,
 'villain': 191,
 'most': 192,
 'likely': 193,
 'give': 194,
 'mercy': 195,
 'united': 196,
 'states': 197,
 'government': 198,
 'still': 199,
 'blacklist': 200,
 'employment': 201,
 'etc': 202,
 'citizens': 203,
 'because': 204,
 'their': 205,
 'political': 206,
 'views': 207,
 'travel': 208,
 'website': 209,
 'spain': 210,
 'people': 211,
 'think': 212,
 'obama': 213,
 'will': 214,
 'try': 215,
 'take': 216,
 'guns': 217,
 'away': 218,
 'year': 219,
 'old': 220,
 'improve': 221,
 'skills': 222,
 'or': 223,
 'become': 224,
 'entrepreneur': 225,
 'next': 226,
 'few': 227,
 'years': 228,
 'girlfriend': 229,
 'asks': 230,
 'her': 231,
 'boyfriend': 232,
 'did': 233,
 'choose': 234,
 'makes': 235,
 'reply': 236,
 'we': 237,
 'ups': 238,
 'stall': 239,
 'aka': 240,
 'wings': 241,
 'fully': 242,
 'swept': 243,
 'back': 244,
 'slavs': 245,
 'squat': 246,
 'expect': 247,
 'cognizant': 248,
 'confirmation': 249,
 'mail': 250,
 'month': 251,
 'day': 252,
 'trading': 253,
 'being': 254,
 'kid': 255,
 'rebel': 256,
 'worth': 257,
 'long': 258,
 'run': 259,
 'universities': 260,
 'record': 261,
 'recruit': 262,
 'new': 263,
 'grads': 264,
 'majors': 265,
 'looking': 266,
 'quickest': 267,
 'instagram': 268,
 'followers': 269,
 'darth': 270,
 'vader': 271,
 'fought': 272,
 'maul': 273,
 'star': 274,
 'wars': 275,
 'legends': 276,
 'stages': 277,
 'breaking': 278,
 'up': 279,
 'between': 280,
 'couple': 281,
 'happens': 282,
 'after': 283,
 'emotionally': 284,
 'whether': 285,
 'its': 286,
 'male': 287,
 'female': 288,
 'examples': 289,
 'products': 290,
 'crude': 291,
 'oil': 292,
 'career': 293,
 'launcher': 294,
 'rib': 295,
 'grade': 296,
 'preparation': 297,
 'blu': 298,
 'ray': 299,
 'play': 300,
 'regular': 301,
 'player': 302,
 'if': 303,
 'she': 304,
 'always': 305,
 'sad': 306,
 'memorable': 307,
 'have': 308,
 'ever': 309,
 'eaten': 310,
 'get': 311,
 'affects': 312,
 'as': 313,
 'tax': 314,
 'officers': 315,
 'difficult': 316,
 'into': 317,
 'sri': 318,
 'who': 319,
 'israel': 320,
 'friend': 321,
 'rap': 322,
 'songs': 323,
 'dance': 324,
 'suddenly': 325,
 'logged': 326,
 'off': 327,
 'email': 328,
 'cannot': 329,
 'remember': 330,
 'password': 331,
 'just': 332,
 'realized': 333,
 'recovery': 334,
 'no': 335,
 'longer': 336,
 'alive': 337,
 'ways': 338,
 'french': 339,
 'download': 340,
 'content': 341,
 'kicks': 342,
 'torrent': 343,
 'without': 344,
 'registration': 345,
 'normal': 346,
 'dark': 347,
 'ring': 348,
 'around': 349,
 'iris': 350,
 'eye': 351,
 'harry': 352,
 'potter': 353,
 'book': 354,
 'cursed': 355,
 'child': 356,
 'depressed': 357,
 'where': 358,
 'european': 359,
 'family': 360,
 'office': 361,
 'database': 362,
 'java': 363,
 'programming': 364,
 'language': 365,
 'made': 366,
 'store': 367,
 'energy': 368,
 'produced': 369,
 'lightning': 370,
 'review': 371,
 'performance': 372,
 'testing': 373,
 'cost': 374,
 'privacy': 375,
 'germany': 376,
 'come': 377,
 'else': 378,
 'lost': 379,
 'gain': 380,
 'types': 381,
 'immunity': 382,
 'narcissistic': 383,
 'personality': 384,
 'disorder': 385,
 'speak': 386,
 'english': 387,
 'fluently': 388,
 'helpful': 389,
 'quickbooks': 390,
 'auto': 391,
 'data': 392,
 'support': 393,
 'phone': 394,
 'number': 395,
 'recover': 396,
 'corrupted': 397,
 'files': 398,
 'richest': 399,
 'gambler': 400,
 'all': 401,
 'reach': 402,
 'his': 403,
 'level': 404,
 'fire': 405,
 'bullet': 406,
 'backward': 407,
 'aircraft': 408,
 'going': 409,
 'faster': 410,
 'than': 411,
 'backwards': 412,
 'prevent': 413,
 'breast': 414,
 'cancer': 415,
 'log': 416,
 'out': 417,
 'account': 418,
 'purpose': 419,
 'life': 420,
 'bop': 421,
 'strip': 422,
 'muslims': 423,
 'christians': 424,
 'indian': 425,
 'citizenship': 426,
 'put': 427,
 'them': 428,
 'boats': 429,
 'rohingya': 430,
 'burma': 431,
 'right': 432,
 'etiquette': 433,
 'wishing': 434,
 'jehovah': 435,
 'witness': 436,
 'happy': 437,
 'birthday': 438,
 'wants': 439,
 'open': 440,
 'commercial': 441,
 'pm': 442,
 'radio': 443,
 'station': 444,
 'any': 445,
 'city': 446,
 'procedure': 447,
 'swiss': 448,
 'despise': 449,
 'asians': 450,
 'high': 451,
 'salary': 452,
 'income': 453,
 'jobs': 454,
 'field': 455,
 'biotechnology': 456,
 'height': 457,
 'also': 458,
 'were': 459,
 'major': 460,
 'effects': 461,
 'cambodia': 462,
 'earthquake': 463,
 'these': 464,
 'kamchatka': 465,
 'earthquakes': 466,
 'difference': 467,
 'fairness': 468,
 'gaming': 469,
 'laptop': 470,
 'under': 471,
 'warrior': 472,
 'proving': 473,
 'grounds': 474,
 'part': 475,
 'reference': 476,
 'class': 477,
 'national': 478,
 'institute': 479,
 'technology': 480,
 'kurukshetra': 481,
 'social': 482,
 'nick': 483,
 'surathkal': 484,
 'romantic': 485,
 'movies': 486,
 'causes': 487,
 'nightmare': 488,
 'abstract': 489,
 'expressionism': 490,
 'painting': 491,
 'printing': 492,
 'work': 493,
 'attend': 494,
 'catch': 495,
 'jeremy': 496,
 'earnhardt': 497,
 'horcrux': 498,
 'associate': 499,
 'product': 500,
 'manager': 501,
 'programs': 502,
 'early': 503,
 'join': 504,
 'management': 505,
 'rewarding': 506,
 'skype': 507,
 'busy': 508,
 'there': 509,
 'really': 510,
 'war': 511,
 'pakistan': 512,
 'over': 513,
 'fri': 514,
 'attack': 515,
 'ronald': 516,
 'reagan': 517,
 'mannerism': 518,
 'speech': 519,
 'strategies': 520,
 'union': 521,
 'civil': 522,
 'fiction': 523,
 'novel': 524,
 'forgot': 525,
 'recent': 526,
 'demonisation': 527,
 'results': 528,
 'higher': 529,
 'gap': 530,
 'heard': 531,
 'hacking': 532,
 'love': 533,
 'pity': 534,
 'competitive': 535,
 'hiring': 536,
 'republic': 537,
 'bank': 538,
 'helps': 539,
 'spam': 540,
 'ranking': 541,
 'adjustment': 542,
 'search': 543,
 'watch': 544,
 'subtitles': 545,
 'powerful': 546,
 'country': 547,
 'world': 548,
 'obtain': 549,
 'instant': 550,
 'ulcer': 551,
 'pain': 552,
 'relief': 553,
 'china': 554,
 'food': 555,
 'taking': 556,
 'advantage': 557,
 'cry': 558,
 'stick': 559,
 'tongues': 560,
 'pictures': 561,
 'ending': 562,
 'depressing': 563,
 'mind': 564,
 'blowing': 565,
 'computer': 566,
 'tools': 567,
 'exist': 568,
 'know': 569,
 'toothbrush': 570,
 'wet': 571,
 'dry': 572,
 'before': 573,
 'applying': 574,
 'toothpaste': 575,
 'question': 576,
 'marked': 577,
 'needing': 578,
 'improvement': 579,
 'neutral': 580,
 'state': 581,
 'buffer': 582,
 'mineral': 583,
 'holds': 584,
 'highest': 585,
 'electrical': 586,
 'charge': 587,
 'greatest': 588,
 'mystery': 589,
 'universe': 590,
 'alternative': 591,
 'machine': 592,
 'learning': 593,
 'block': 594,
 'sanctions': 595,
 'against': 596,
 'cash': 597,
 'mohammad': 598,
 'jim': 599,
 'chief': 600,
 'mood': 601,
 'char': 602,
 'future': 603,
 'budget': 604,
 'excessive': 605,
 'amounts': 606,
 'vitamin': 607,
 'cause': 608,
 'miscarriage': 609,
 'ash': 610,
 'glass': 611,
 'pay': 612,
 'scale': 613,
 'two': 614,
 'access': 615,
 'turbo': 616,
 'mantras': 617,
 'six': 618,
 'party': 619,
 'talks': 620,
 'successful': 621,
 'register': 622,
 'domain': 623,
 'site': 624,
 'older': 625,
 'men': 626,
 'attracted': 627,
 'young': 628,
 'women': 629,
 'strongest': 630,
 'structure': 631,
 'shape': 632,
 'compression': 633,
 'matter': 634,
 'humans': 635,
 'selfish': 636,
 'evil': 637,
 'endocytosis': 638,
 'active': 639,
 'passive': 640,
 'transport': 641,
 'hair': 642,
 'bald': 643,
 'head': 644,
 'ideal': 645,
 'retirement': 646,
 'our': 647,
 'stance': 648,
 'websites': 649,
 'escorts': 650,
 'polo': 651,
 'diesel': 652,
 'grand': 653,
 'petrol': 654,
 'black': 655,
 'hole': 656,
 'mass': 657,
 'morgan': 658,
 'freeman': 659,
 'correct': 660,
 'says': 661,
 'only': 662,
 'stop': 663,
 'racism': 664,
 'talking': 665,
 'fab': 666,
 'currently': 667,
 'offer': 668,
 'employees': 669,
 'stock': 670,
 'options': 671,
 'russ': 672,
 'distribute': 673,
 'identical': 674,
 'pencils': 675,
 'each': 676,
 'least': 677,
 'pencil': 678,
 'hire': 679,
 'jerry': 680,
 'seinfeld': 681,
 'hours': 682,
 'days': 683,
 'late': 684,
 'rabies': 685,
 'vaccine': 686,
 'possible': 687,
 'non': 688,
 'bite': 689,
 'exposure': 690,
 'britain': 691,
 'ruled': 692,
 'afraid': 693,
 'working': 694,
 'red': 695,
 'keep': 696,
 'keys': 697,
 'age': 698,
 'lose': 699,
 'virginity': 700,
 'could': 701,
 'smoke': 702,
 'secretly': 703,
 'monetize': 704,
 'videos': 705,
 'upload': 706,
 'copyright': 707,
 'then': 708,
 'chances': 709,
 'may': 710,
 'switch': 711,
 'canon': 712,
 'leila': 713,
 'lux': 714,
 'members': 715,
 'moderation': 716,
 'nobody': 717,
 'answer': 718,
 'funniest': 719,
 'joke': 720,
 'got': 721,
 'london': 722,
 '£': 723,
 'deduction': 724,
 'plus': 725,
 'advice': 726,
 'monthly': 727,
 'expenses': 728,
 'saving': 729,
 'stereotypes': 730,
 'kingdom': 731,
 'twitter': 732,
 'business': 733,
 'source': 734,
 'transfer': 735,
 'skill': 736,
 'paypal': 737,
 'earphone': 738,
 'deep': 739,
 'bass': 740,
 'eligible': 741,
 'susanna': 742,
 'saudi': 743,
 'jana': 744,
 'forward': 745,
 'engineering': 746,
 'fields': 747,
 'suit': 748,
 'abusing': 749,
 'gross': 750,
 'towns': 751,
 'kerala': 752,
 'confidence': 753,
 'anyone': 754,
 'see': 755,
 'relation': 756,
 'greek': 757,
 'gods': 758,
 'hindu': 759,
 'apple': 760,
 'music': 761,
 'notify': 762,
 'fixed': 763,
 'fund': 764,
 'live': 765,
 'cologne': 766,
 'robert': 767,
 'de': 768,
 'nero': 769,
 'al': 770,
 'pacino': 771,
 'more': 772,
 'prefer': 773,
 'small': 774,
 'families': 775,
 'animals': 776,
 'simple': 777,
 'stupid': 778,
 'deleted': 779,
 'chats': 780,
 'addicted': 781,
 'hired': 782,
 'private': 783,
 'ordered': 784,
 'follow': 785,
 'other': 786,
 'startup': 787,
 'accelerator': 788,
 'check': 789,
 'wifi': 790,
 'history': 791,
 'android': 792,
 'phones': 793,
 'significance': 794,
 'battle': 795,
 'somme': 796,
 'this': 797,
 'contrast': 798,
 'rostov': 799,
 'creative': 800,
 'college': 801,
 'admissions': 802,
 'essay': 803,
 'happen': 804,
 'cover': 805,
 'patch': 806,
 'pursue': 807,
 'different': 808,
 'things': 809,
 'ben': 810,
 'affect': 811,
 'shine': 812,
 'christian': 813,
 'bale': 814,
 'batman': 815,
 'start': 816,
 'hyderabad': 817,
 'possessive': 818,
 'wife': 819,
 'lord': 820,
 'krishna': 821,
 'combination': 822,
 'courses': 823,
 'along': 824,
 'enhance': 825,
 'screenshot': 826,
 'mac': 827,
 'executive': 828,
 'recruiter': 829,
 'psychological': 830,
 'need': 831,
 'collecting': 832,
 'fulfill': 833,
 'must': 834,
 'shows': 835,
 'die': 836,
 'fluent': 837,
 'chinese': 838,
 'demobilization': 839,
 'rupees': 840,
 'notes': 841,
 'real': 842,
 'estate': 843,
 'sector': 844,
 'easiest': 845,
 'billionaire': 846,
 'willing': 847,
 'free': 848,
 'lectures': 849,
 'conduct': 850,
 'workshop': 851,
 'colleges': 852,
 'robotics': 853,
 'hate': 854,
 'hillary': 855,
 'clinton': 856,
 'periods': 857,
 'regarded': 858,
 'unclean': 859,
 'such': 860,
 'prevented': 861,
 'rituals': 862,
 'hinduism': 863,
 'atheism': 864,
 'lack': 865,
 'belief': 866,
 'term': 867,
 'god': 868,
 'jack': 869,
 'dorsey': 870,
 'quotes': 871,
 'lessons': 872,
 'assassin': 873,
 'creed': 874,
 'series': 875,
 'inlet': 876,
 'printers': 877,
 'color': 878,
 'ink': 879,
 'documents': 880,
 'creativity': 881,
 'important': 882,
 'continue': 883,
 'presidential': 884,
 'campaign': 885,
 'democratic': 886,
 'candidate': 887,
 'headphones': 888,
 'antenna': 889,
 'channels': 890,
 'mobile': 891,
 'companies': 892,
 'install': 893,
 'inbuilt': 894,
 'able': 895,
 'growth': 896,
 'technologies': 897,
 'automation': 898,
 'engineers': 899,
 'apart': 900,
 'disadvantages': 901,
 'listing': 902,
 'derivatives': 903,
 'object': 904,
 'position': 905,
 'respect': 906,
 'continuous': 907,
 'neutron': 908,
 'spa': 909,
 'enough': 910,
 'top': 911,
 'harvard': 912,
 'profitable': 913,
 'trade': 914,
 'binary': 915,
 'utilize': 916,
 'avoid': 917,
 'depression': 918,
 'security': 919,
 'earn': 920,
 'code': 921,
 'japan': 922,
 'sentences': 923,
 'word': 924,
 'another': 925,
 'billion': 926,
 'dollar': 927,
 'lottery': 928,
 'jackpot': 929,
 'scary': 930,
 'drive': 931,
 'road': 932,
 'hand': 933,
 'given': 934,
 'turns': 935,
 'create': 936,
 'shell': 937,
 'terminal': 938,
 'linux': 939,
 'cognition': 940,
 'perception': 941,
 'cowl': 942,
 'total': 943,
 'waiting': 944,
 'list': 945,
 'generations': 946,
 'champions': 947,
 'league': 948,
 'drinking': 949,
 'liners': 950,
 'unhealthy': 951,
 'great': 952,
 'lakes': 953,
 'wildlife': 954,
 'lake': 955,
 'presa': 956,
 'porn': 957,
 'stars': 958,
 'supporters': 959,
 'feel': 960,
 'walking': 961,
 'promises': 962,
 'worried': 963,
 'others': 964,
 'opinions': 965,
 'potty': 966,
 'train': 967,
 'months': 968,
 'pinball': 969,
 'jump': 970,
 'rope': 971,
 'five': 972,
 'minutes': 973,
 'calories': 974,
 'test': 975,
 'gate': 976,
 'stream': 977,
 'material': 978,
 'understanding': 979,
 'algorithmic': 980,
 'analysis': 981,
 'newbie': 982,
 'temperament': 983,
 'husky': 984,
 'mix': 985,
 'balls': 986,
 'weigh': 987,
 'has': 988,
 'weight': 989,
 'heavier': 990,
 'lighter': 991,
 'odd': 992,
 'ball': 993,
 'weighs': 994,
 'raisin': 995,
 'walter': 996,
 'beneath': 997,
 'argue': 998,
 'signs': 999,
 ...}

In [23]:
VOCAB_SIZE = len(vocab)
VOCAB_SIZE

28549

In [24]:
# tokenize a text --> consider upto first 25 words only
# if there are <25 words, append zeros at the end to make 25 words exactly
def encode(sent, max_words=25):
    # in word2idx.get(w,1) --> if w doesn't exist in vocab, return index 1 <'unk'>
    ids = [word2idx.get(w,1) for w in tokenize(sent)][:max_words]
    # append 0 at the end, 0=<'pad'> to make the length 25 exactly
    ids += [0] * (max_words - len(ids))
    return ids

In [25]:
MAX_WORDS = 30
df_train['ids1'] = df_train['question1'].apply(lambda s: encode(s, MAX_WORDS))
df_train['ids2'] = df_train['question2'].apply(lambda s: encode(s, MAX_WORDS))
df_train.sample(5)

,question1,question2,is_duplicate,ids1,ids2
54016,what are some signs that someone is a java a a,what are some signs someone is a a a girlfriend,0,"[2, 96, 159, 999, 57, 146, 3, 30, 363, 30, 30,...","[2, 96, 159, 999, 146, 3, 30, 30, 30, 229, 0, ..."
8293,can you see who viewed your instagram,can someone see if you have viewed public inst...,1,"[22, 69, 755, 319, 3965, 91, 268, 0, 0, 0, 0, ...","[22, 146, 755, 303, 69, 308, 3965, 2384, 268, ..."
276395,is the university of vermont a good school,how good is the university of vermont,1,"[3, 4, 1353, 15, 4119, 30, 65, 1967, 0, 0, 0, ...","[21, 65, 3, 4, 1353, 15, 4119, 0, 0, 0, 0, 0, ..."
125494,what is a chicken tenderloin,what can one do with the flat end of a beef te...,0,"[2, 3, 30, 1589, 5941, 0, 0, 0, 0, 0, 0, 0, 0,...","[2, 22, 40, 68, 125, 4, 3290, 1145, 15, 30, 80..."
9330,is hard work best or smart work best,which one is the best to choose smart work or ...,1,"[3, 1675, 493, 137, 223, 1001, 493, 137, 0, 0,...","[39, 40, 3, 4, 137, 8, 234, 1001, 493, 223, 16..."

In [26]:
# Skip-gram Word2Vec with negative sampling (using custom nn.Module on GPU)

WINDOW = 4
EMBED_DIM = 128
NEG_SAMPLES = 5

In [27]:
# for each row, a pair is (curr_word, +-WINDOW word)
def build_skipgram_pairs(token_list, window=WINDOW):
    pairs = []
    for tokens in token_list:
        ids = [word2idx.get(w,1) for w in tokens]
        n = len(ids)
        for i, center in enumerate(ids):
            lo = max(0, i - window)
            hi = min(n, i + window + 1)
            for j in range(lo, hi):
                if j != i:
                    pairs.append((center, ids[j]))
    return pairs

In [28]:
sentence_tokens = [tokenize(s) for s in pd.concat([df_train['question1'],df_train['question2']])]
pairs = build_skipgram_pairs(sentence_tokens)
pairs

[(2, 3),
 (2, 4),
 (2, 5),
 (2, 6),
 (3, 2),
 (3, 4),
 (3, 5),
 (3, 6),
 (3, 5),
 (4, 2),
 (4, 3),
 (4, 5),
 (4, 6),
 (4, 5),
 (4, 7),
 (5, 2),
 (5, 3),
 (5, 4),
 (5, 6),
 (5, 5),
 (5, 7),
 (5, 8),
 (6, 2),
 (6, 3),
 (6, 4),
 (6, 5),
 (6, 5),
 (6, 7),
 (6, 8),
 (6, 9),
 (5, 3),
 (5, 4),
 (5, 5),
 (5, 6),
 (5, 7),
 (5, 8),
 (5, 9),
 (5, 10),
 (7, 4),
 (7, 5),
 (7, 6),
 (7, 5),
 (7, 8),
 (7, 9),
 (7, 10),
 (7, 11),
 (8, 5),
 (8, 6),
 (8, 5),
 (8, 7),
 (8, 9),
 (8, 10),
 (8, 11),
 (8, 12),
 (9, 6),
 (9, 5),
 (9, 7),
 (9, 8),
 (9, 10),
 (9, 11),
 (9, 12),
 (9, 10),
 (10, 5),
 (10, 7),
 (10, 8),
 (10, 9),
 (10, 11),
 (10, 12),
 (10, 10),
 (10, 13),
 (11, 7),
 (11, 8),
 (11, 9),
 (11, 10),
 (11, 12),
 (11, 10),
 (11, 13),
 (12, 8),
 (12, 9),
 (12, 10),
 (12, 11),
 (12, 10),
 (12, 13),
 (10, 9),
 (10, 10),
 (10, 11),
 (10, 12),
 (10, 13),
 (13, 10),
 (13, 11),
 (13, 12),
 (13, 10),
 (2, 3),
 (2, 4),
 (2, 14),
 (2, 15),
 (3, 2),
 (3, 4),
 (3, 14),
 (3, 15),
 (3, 16),
 (4, 2),
 (4, 3),
 (4, 14),
 (4, 15),
 (4, 16),
 (4, 17),
 (14, 2),
 (14, 3),
 (14, 4),
 (14, 15),
 (14, 16),
 (14, 17),
 (14, 18),
 (15, 2),
 (15, 3),
 (15, 4),
 (15, 14),
 (15, 16),
 (15, 17),
 (15, 18),
 (15, 19),
 (16, 3),
 (16, 4),
 (16, 14),
 (16, 15),
 (16, 17),
 (16, 18),
 (16, 19),
 (16, 20),
 (17, 4),
 (17, 14),
 (17, 15),
 (17, 16),
 (17, 18),
 (17, 19),
 (17, 20),
 (18, 14),
 (18, 15),
 (18, 16),
 (18, 17),
 (18, 19),
 (18, 20),
 (19, 15),
 (19, 16),
 (19, 17),
 (19, 18),
 (19, 20),
 (20, 16),
 (20, 17),
 (20, 18),
 (20, 19),
 (21, 22),
 (21, 18),
 (21, 23),
 (21, 4),
 (22, 21),
 (22, 18),
 (22, 23),
 (22, 4),
 (22, 24),
 (18, 21),
 (18, 22),
 (18, 23),
 (18, 4),
 (18, 24),
 (18, 15),
 (23, 21),
 (23, 22),
 (23, 18),
 (23, 4),
 (23, 24),
 (23, 15),
 (23, 25),
 (4, 21),
 (4, 22),
 (4, 18),
 (4, 23),
 (4, 24),
 (4, 15),
 (4, 25),
 (4, 26),
 (24, 22),
 (24, 18),
 (24, 23),
 (24, 4),
 (24, 15),
 (24, 25),
 (24, 26),
 (24, 27),
 (15, 18),
 (15, 23),
 (15, 4),
 (15, 24),
 (15, 25),
 (15, 26),
 (15, 27),
 (15, 28),
 (25, 23),
 (25, 4),
 (25, 24),
 (25, 15),
 (25, 26),
 (25, 27),
 (25, 28),
 (25, 29),
 (26, 4),
 (26, 24),
 (26, 15),
 (26, 25),
 (26, 27),
 (26, 28),
 (26, 29),
 (26, 30),
 (27, 24),
 (27, 15),
 (27, 25),
 (27, 26),
 (27, 28),
 (27, 29),
 (27, 30),
 (27, 31),
 (28, 15),
 (28, 25),
 (28, 26),
 (28, 27),
 (28, 29),
 (28, 30),
 (28, 31),
 (29, 25),
 (29, 26),
 (29, 27),
 (29, 28),
 (29, 30),
 (29, 31),
 (30, 26),
 (30, 27),
 (30, 28),
 (30, 29),
 (30, 31),
 (31, 27),
 (31, 28),
 (31, 29),
 (31, 30),
 (32, 33),
 (32, 18),
 (32, 34),
 (32, 35),
 (33, 32),
 (33, 18),
 (33, 34),
 (33, 35),
 (33, 36),
 (18, 32),
 (18, 33),
 (18, 34),
 (18, 35),
 (18, 36),
 (18, 21),
 (34, 32),
 (34, 33),
 (34, 18),
 (34, 35),
 (34, 36),
 (34, 21),
 (34, 22),
 (35, 32),
 (35, 33),
 (35, 18),
 (35, 34),
 (35, 36),
 (35, 21),
 (35, 22),
 (35, 18),
 (36, 33),
 (36, 18),
 (36, 34),
 (36, 35),
 (36, 21),
 (36, 22),
 (36, 18),
 (36, 37),
 (21, 18),
 (21, 34),
 (21, 35),
 (21, 36),
 (21, 22),
 (21, 18),
 (21, 37),
 (21, 38),
 (22, 34),
 (22, 35),
 (22, 36),
 (22, 21),
 (22, 18),
 (22, 37),
 (22, 38),
 (18, 35),
 (18, 36),
 (18, 21),
 (18, 22),
 (18, 37),
 (18, 38),
 (37, 36),
 (37, 21),
 (37, 22),
 (37, 18),
 (37, 38),
 (38, 21),
 (38, 22),
 (38, 18),
 (38, 37),
 (39, 40),
 (39, 41),
 (39, 10),
 (39, 42),
 (40, 39),
 (40, 41),
 (40, 10),
 (40, 42),
 (40, 43),
 (41, 39),
 (41, 40),
 (41, 10),
 (41, 42),
 (41, 43),
 (41, 44),
 (10, 39),
 (10, 40),
 (10, 41),
 (10, 42),
 (10, 43),
 (10, 44),
 (10, 45),
 (42, 39),
 (42, 40),
 (42, 41),
 (42, 10),
 (42, 43),
 (42, 44),
 (42, 45),
 (42, 46),
 (43, 40),
 (43, 41),
 (43, 10),
 (43, 42),
 (43, 44),
 (43, 45),
 (43, 46),
 (43, 47),
 (44, 41),
 (44, 10),
 (44, 42),
 (44, 43),
 (44, 45),
 (44, 46),
 (44, 47),
 (44, 48),
 (45, 10),
 (45, 42),
 (45, 43),
 (45, 44),
 (45, 46),
 (45, 47),
 (45, 48),
 (45, 18),
 (46, 42),
 (46, 43),
 (46, 44),
 (46, 45),
 (46, 47),
 (46, 48),
 (46, 18),
 (46, 49),
 (47, 43),
 (47, 44),
 (47, 45),
 (47, 46),
 (47, 48),
 (47, 18),
 (47, 49),
 (48, 44),
 (48, 45),
 (48, 46),
 (48, 47),
 (48, 18),
 (48, 49),
 (18, 45),
 (18, 46),
 (18, 47),
 (18, 48),
 (18, 49),
 (49, 46),
 (49, 47),
 (49, 48),
 (49, 18),
 (50, 18),
 (50, 33),
 (50, 30),
 (50, 51),
 (18, 50),
 (18, 33),
 (18, 30),
 (18, 51),
 (18, 52),
 (33, 50),
 (33, 18),
 (33, 30),
 (33, 51),
 (33, 52),
 (33, 53),
 (30, 50),
 (30, 18),
 (30, 33),
 (30, 51),
 (30, 52),
 (30, 53),
 (30, 54),
 (51, 50),
 (51, 18),
 (51, 33),
 (51, 30),
 (51, 52),
 (51, 53),
 (51, 54),
 (51, 47),
 (52, 18),
 (52, 33),
 (52, 30),
 (52, 51),
 (52, 53),
 (52, 54),
 (52, 47),
 (52, 53),
 (53, 33),
 (53, 30),
 (53, 51),
 (53, 52),
 (53, 54),
 (53, 47),
 (53, 53),
 (53, 55),
 (54, 30),
 (54, 51),
 (54, 52),
 (54, 53),
 (54, 47),
 (54, 53),
 (54, 55),
 (54, 2),
 (47, 51),
 (47, 52),
 (47, 53),
 (47, 54),
 (47, 53),
 (47, 55),
 (47, 2),
 (47, 56),
 (53, 52),
 (53, 53),
 (53, 54),
 (53, 47),
 (53, 55),
 (53, 2),
 (53, 56),
 (53, 57),
 (55, 53),
 (55, 54),
 (55, 47),
 (55, 53),
 (55, 2),
 (55, 56),
 (55, 57),
 (55, 58),
 (2, 54),
 (2, 47),
 (2, 53),
 (2, 55),
 (2, 56),
 (2, 57),
 (2, 58),
 (2, 59),
 (56, 47),
 (56, 53),
 (56, 55),
 (56, 2),
 (56, 57),
 (56, 58),
 (56, 59),
 (56, 60),
 (57, 53),
 (57, 55),
 (57, 2),
 (57, 56),
 (57, 58),
 (57, 59),
 (57, 60),
 (58, 55),
 (58, 2),
 (58, 56),
 (58, 57),
 (58, 59),
 (58, 60),
 (59, 2),
 (59, 56),
 (59, 57),
 (59, 58),
 (59, 60),
 (60, 56),
 (60, 57),
 (60, 58),
 (60, 59),
 (61, 18),
 (61, 62),
 (61, 63),
 (18, 61),
 (18, 62),
 (18, 63),
 (62, 61),
 (62, 18),
 (62, 63),
 (63, 61),
 (63, 18),
 (63, 62),
 (21, 22),
 (21, 18),
 (21, 64),
 (21, 30),
 (22, 21),
 (22, 18),
 (22, 64),
 (22, 30),
 (22, 65),
 (18, 21),
 (18, 22),
 (18, 64),
 (18, 30),
 (18, 65),
 (18, 66),
 (64, 21),
 (64, 22),
 (64, 18),
 (64, 30),
 (64, 65),
 (64, 66),
 (30, 21),
 (30, 22),
 (30, 18),
 (30, 64),
 (30, 65),
 (30, 66),
 (65, 22),
 (65, 18),
 (65, 64),
 (65, 30),
 (65, 66),
 (66, 18),
 (66, 64),
 (66, 30),
 (66, 65),
 (67, 68),
 (67, 69),
 (67, 70),
 (67, 1),
 (68, 67),
 (68, 69),
 (68, 70),
 (68, 1),
 (68, 71),
 (69, 67),
 (69, 68),
 (69, 70),
 (69, 1),
 (69, 71),
 (69, 15),
 (70, 67),
 (70, 68),
 (70, 69),
 (70, 1),
 (70, 71),
 (70, 15),
 (70, 1),
 (1, 67),
 (1, 68),
 (1, 69),
 (1, 70),
 (1, 71),
 (1, 15),
 (1, 1),
 (71, 68),
 (71, 69),
 (71, 70),
 (71, 1),
 (71, 15),
 (71, 1),
 (15, 69),
 (15, 70),
 (15, 1),
 (15, 71),
 (15, 1),
 (1, 70),
 (1, 1),
 (1, 71),
 (1, 15),
 (72, 73),
 (72, 22),
 (72, 18),
 (72, 74),
 (73, 72),
 (73, 22),
 (73, 18),
 (73, 74),
 (73, 25),
 (22, 72),
 (22, 73),
 (22, 18),
 (22, 74),
 (22, 25),
 (22, 75),
 (18, 72),
 (18, 73),
 (18, 22),
 (18, 74),
 (18, 25),
 (18, 75),
 (18, 72),
 (74, 72),
 (74, 73),
 (74, 22),
 (74, 18),
 (74, 25),
 (74, 75),
 (74, 72),
 (74, 76),
 (25, 73),
 (25, 22),
 (25, 18),
 (25, 74),
 (25, 75),
 (25, 72),
 (25, 76),
 (75, 22),
 (75, 18),
 (75, 74),
 (75, 25),
 (75, 72),
 (75, 76),
 (72, 18),
 (72, 74),
 (72, 25),
 (72, 75),
 (72, 76),
 (76, 74),
 (76, 25),
 (76, 75),
 (76, 72),
 (77, 8),
 (77, 78),
 (77, 79),
 (77, 15),
 (8, 77),
 (8, 78),
 (8, 79),
 (8, 15),
 (8, 80),
 (78, 77),
 (78, 8),
 (78, 79),
 (78, 15),
 (78, 80),
 (78, 29),
 (79, 77),
 (79, 8),
 (79, 78),
 (79, 15),
 (79, 80),
 (79, 29),
 (79, 81),
 (15, 77),
 (15, 8),
 (15, 78),
 (15, 79),
 (15, 80),
 (15, 29),
 (15, 81),
 (15, 82),
 (80, 8),
 (80, 78),
 (80, 79),
 (80, 15),
 (80, 29),
 (80, 81),
 (80, 82),
 (29, 78),
 (29, 79),
 (29, 15),
 (29, 80),
 (29, 81),
 (29, 82),
 (81, 79),
 (81, 15),
 (81, 80),
 (81, 29),
 (81, 82),
 (82, 15),
 (82, 80),
 (82, 29),
 (82, 81),
 (21, 68),
 (21, 18),
 (21, 83),
 (21, 47),
 (68, 21),
 (68, 18),
 (68, 83),
 (68, 47),
 (68, 78),
 (18, 21),
 (18, 68),
 (18, 83),
 (18, 47),
 (18, 78),
 (18, 25),
 (83, 21),
 (83, 68),
 (83, 18),
 (83, 47),
 (83, 78),
 (83, 25),
 (83, 84),
 (47, 21),
 (47, 68),
 (47, 18),
 (47, 83),
 (47, 78),
 (47, 25),
 (47, 84),
 (47, 85),
 (78, 68),
 (78, 18),
 (78, 83),
 (78, 47),
 (78, 25),
 (78, 84),
 (78, 85),
 (25, 18),
 (25, 83),
 (25, 47),
 (25, 78),
 (25, 84),
 (25, 85),
 (84, 83),
 (84, 47),
 (84, 78),
 (84, 25),
 (84, 85),
 (85, 47),
 (85, 78),
 (85, 25),
 (85, 84),
 (2, 22),
 (2, 86),
 (2, 87),
 (2, 88),
 (22, 2),
 (22, 86),
 (22, 87),
 (22, 88),
 (22, 8),
 (86, 2),
 (86, 22),
 (86, 87),
 (86, 88),
 (86, 8),
 (86, 89),
 (87, 2),
 (87, 22),
 (87, 86),
 (87, 88),
 (87, 8),
 (87, 89),
 (88, 2),
 (88, 22),
 (88, 86),
 (88, 87),
 (88, 8),
 (88, 89),
 (8, 22),
 (8, 86),
 (8, 87),
 (8, 88),
 (8, 89),
 (89, 86),
 (89, 87),
 (89, 88),
 (89, 8),
 (2, 90),
 (2, 91),
 (2, 92),
 (2, 93),
 (90, 2),
 (90, 91),
 (90, 92),
 (90, 93),
 (90, 94),
 (91, 2),
 (91, 90),
 (91, 92),
 (91, 93),
 (91, 94),
 (91, 95),
 (92, 2),
 (92, 90),
 (92, 91),
 (92, 93),
 (92, 94),
 (92, 95),
 (93, 2),
 (93, 90),
 (93, 91),
 (93, 92),
 (93, 94),
 (93, 95),
 (94, 90),
 (94, 91),
 (94, 92),
 (94, 93),
 (94, 95),
 (95, 91),
 (95, 92),
 (95, 93),
 (95, 94),
 (2, 96),
 (2, 4),
 (2, 97),
 (2, 8),
 (96, 2),
 (96, 4),
 (96, 97),
 (96, 8),
 (96, 98),
 (4, 2),
 (4, 96),
 (4, 97),
 (4, 8),
 (4, 98),
 (4, 91),
 (97, 2),
 (97, 96),
 (97, 4),
 (97, 8),
 (97, 98),
 (97, 91),
 (97, 99),
 (8, 2),
 (8, 96),
 (8, 4),
 (8, 97),
 (8, 98),
 (8, 91),
 (8, 99),
 (8, 100),
 (98, 96),
 (98, 4),
 (98, 97),
 (98, 8),
 (98, 91),
 (98, 99),
 (98, 100),
 (98, 30),
 (91, 4),
 (91, 97),
 (91, 8),
 (91, 98),
 (91, 99),
 (91, 100),
 (91, 30),
 (91, 101),
 (99, 97),
 (99, 8),
 (99, 98),
 (99, 91),
 (99, 100),
 (99, 30),
 (99, 101),
 (99, 102),
 (100, 8),
 (100, 98),
 (100, 91),
 (100, 99),
 (100, 30),
 (100, 101),
 (100, 102),
 (100, 8),
 (30, 98),
 (30, 91),
 (30, 99),
 (30, 100),
 (30, 101),
 (30, 102),
 (30, 8),
 (30, 30),
 (101, 91),
 (101, 99),
 (101, 100),
 (101, 30),
 (101, 102),
 (101, 8),
 (101, 30),
 (101, 103),
 (102, 99),
 (102, 100),
 (102, 30),
 (102, 101),
 (102, 8),
 (102, 30),
 (102, 103),
 (102, 104),
 (8, 100),
 (8, 30),
 (8, 101),
 (8, 102),
 (8, 30),
 (8, 103),
 (8, 104),
 (8, 10),
 (30, 30),
 (30, 101),
 (30, 102),
 (30, 8),
 (30, 103),
 (30, 104),
 (30, 10),
 (30, 4),
 (103, 101),
 (103, 102),
 (103, 8),
 (103, 30),
 (103, 104),
 (103, 10),
 (103, 4),
 (103, 105),
 (104, 102),
 (104, 8),
 (104, 30),
 (104, 103),
 (104, 10),
 (104, 4),
 (104, 105),
 (104, 21),
 (10, 8),
 (10, 30),
 (10, 103),
 (10, 104),
 (10, 4),
 (10, 105),
 (10, 21),
 (10, 68),
 (4, 30),
 (4, 103),
 (4, 104),
 (4, 10),
 (4, 105),
 (4, 21),
 (4, 68),
 (4, 106),
 (105, 103),
 (105, 104),
 (105, 10),
 (105, 4),
 (105, 21),
 (105, 68),
 (105, 106),
 (105, 107),
 (21, 104),
 (21, 10),
 (21, 4),
 (21, 105),
 (21, 68),
 (21, 106),
 (21, 107),
 (21, 8),
 (68, 10),
 (68, 4),
 (68, 105),
 (68, 21),
 (68, 106),
 (68, 107),
 (68, 8),
 (68, 4),
 (106, 4),
 (106, 105),
 (106, 21),
 (106, 68),
 (106, 107),
 (106, 8),
 (106, 4),
 (106, 108),
 (107, 105),
 (107, 21),
 ...]

In [29]:
pairs = np.array(pairs, dtype=np.int64)
pairs.shape

(55983960, 2)